<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDnVtiTX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDnVtiTX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDnVtiTX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDnVtiTX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDnVtiTX\App_KernelDevDebugContainer([
    'container.build_hash' => 'DnVtiTX',
    'container.build_id' => '8491c202',
    'container.build_time' => 1691855106,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDnVtiTX');
